project:
  type: website
  output-dir: docs

website:
  title: "Cyber Sciences Events"
  description: "Piloter des événements scientifiques à l'ère des technologies intellectives"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: About
      - href: joMars2026.qmd
        text: "Journées d'études : Mars 2026"
    right:
      - icon: github
        href: https://github.com/samszo/cyberSciencesEvents
  page-footer:
    left: "© Cyber Sciences Events"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
